apiVersion: v1
kind: Service
metadata:
  name: flask-api-svc
  labels:
    app.kubernetes.io/name: flask-api
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: k8s-multiservice-lab
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: flask-api
    app.kubernetes.io/component: api
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http
