apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: flask-api
  labels:
    app.kubernetes.io/name: flask-api
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: k8s-multiservice-lab
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: flask-api
      app.kubernetes.io/component: api
