apiVersion: v1
kind: ServiceAccount
metadata:
  name: flask-api
  labels:
    app.kubernetes.io/name: flask-api
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: k8s-multiservice-lab
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: redis
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/component: cache
    app.kubernetes.io/part-of: k8s-multiservice-lab
automountServiceAccountToken: false
