apiVersion: v1
kind: ResourceQuota
metadata:
  name: stg-compute
  labels:
    app.kubernetes.io/part-of: k8s-multiservice-lab
spec:
  hard:
    requests.cpu: "750m"
    requests.memory: 768Mi
    limits.cpu: "3"
    limits.memory: 2Gi
    pods: "12"
    services: "5"
    configmaps: "10"
    secrets: "10"
